import type { Metadata } from 'next';
import './globals.css';
import clsx from 'clsx';

import { Inter } from 'next/font/google';
import { Inconsolata } from 'next/font/google';

import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

const inconsolata = Inconsolata({
  subsets: ['latin'],
  variable: '--font-inconsolata',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={clsx(inter.variable, inconsolata.variable, 'scroll-smooth')}>
      <body className='text-gray'>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
